<?php

return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'font_dir' => storage_path('fonts/'),
        'font_cache' => storage_path('fonts/'),
        'temp_dir' => storage_path('app/pdf_temp/'),
        'chroot' => realpath(base_path()),
        'enable_font_subsetting' => false,
        'pdf_backend' => 'CPDF',
        'default_media_type' => 'screen',
        'default_paper_size' => 'a4',
        'default_font' => 'Arial',
        'dpi' => 96,
        'enable_php' => false,
        'enable_javascript' => false,
        'enable_remote' => true,
        'font_height_ratio' => 1.1,
        'enable_html5_parser' => true,
        'enable_smart_shrinking' => true,
    ],
    'options' => [
        'isRemoteEnabled' => true,
        'isHtml5ParserEnabled' => true,
        'isFontSubsettingEnabled' => false,
        'defaultFont' => 'Arial',
        'chroot' => realpath(base_path()),
        'enable_remote' => true,
        'enable_php' => false,
        'enable_javascript' => false,
        'enable_smart_shrinking' => true,
        'encoding' => 'UTF-8',
        'dpi' => 96,
        'image_dpi' => 96,
        'image_cache_dir' => storage_path('app/pdf_cache/'),
        'temp_dir' => storage_path('app/pdf_temp/'),
        'log_output_file' => storage_path('logs/pdf.log'),
    ],
]; 